### ISSUE TITLE
life mending bug

### ISSUE THREAD

**Issue by zerevoidd** [Safrodev/Apotheosis-Fabric#10]
my players can spam life mending items in grindstones for free infinite xp, any way to fix or would the mod need to be updated

**Comment by Safrodev** [comment]
This is happens because life mending is a curse enchantment. By default, vanilla does not remove curses in the grindstone.

**Comment by Dark15** [comment]
> This is happens because life mending is a curse enchantment. By default, vanilla does not remove curses in the grindstone.

But when I try to remove the curse enchantment, vanilla won't give me xp. Apotheosis is also.
