### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by Balakay420** [Safrodev/Apotheosis-Fabric#12]
hello! server doesn't crash when I try to join. but this pops up
![image](https://user-images.githubusercontent.com/106470691/172041468-dc0292b8-0bc9-4213-888f-7e7ff29e81fc.png)
ash when I try to join. but this pops up

**Comment by Safrodev** [comment]
Is there anything in the server and client logs?

**Comment by Safrodev** [comment]
Should be fixed in 0.2.71 sorry about that

**Comment by Balakay420** [comment]
My bad I would've posted logs but I fell asleep. Thanks for the fix!
