### ISSUE TITLE
Client stops loading (No crash) 1.18.2

### ISSUE THREAD

**Issue by Gamerbolts** [Safrodev/Apotheosis-Fabric#14]
Hello! I have a huge modpack and it was erroring for me, I did a lot of testing and came to find out that my client would not load when I was on the following versions

MC 1.18.2
Fabric API 0.56.1
Fabric 0.14.8
Apotheosis 0.28
Anvil Fix 1.3.0
Cloth Config 6.2.62

When I try to start the client it stops immediately and does not give me a crash report but this is the [latest.log](https://github.com/Safrodev/Apotheosis-Fabric/files/8961001/latest.log)
 
No idea if it is Apotheosis Anvil Fix or Cloth Config causing it, so I am posting on all githubs. Any help is appreciated. Thank you!

**Comment by Safrodev** [comment]
Yea it looks like Apotheosis is having issues with anvil fix. I'll probably put the anvil fix mixin priority over apotheosis so that you can use that mod's config options and avoid this issue.

**Comment by Safrodev** [comment]
Should be fixed in v0.2.81 :)
