### ISSUE TITLE
Crash after breaking spawner 

### ISSUE THREAD

**Issue by slammaja** [Safrodev/Apotheosis-Fabric#17]
Hi, the game crashes after breaking a spawner with spawner module disabled, with it on it seems ok.
[crash-2022-07-01_16.52.14-server.txt](https://github.com/Safrodev/Apotheosis-Fabric/files/9029861/crash-2022-07-01_16.52.14-server.txt)
.

**Comment by slammaja** [comment]
I play with version 0.2.81

**Comment by Safrodev** [comment]
Will work on a fix soon
