### ISSUE TITLE
[Bug] Seashelf crafting recipe not working 

### ISSUE THREAD

**Issue by Smittlord** [Safrodev/Apotheosis-Fabric#20]
![image](https://user-images.githubusercontent.com/76596031/179410533-eafd806b-92f4-4741-8045-516527885342.png)
Hi, Me and a friend made a custom modpack using Apotheosis called Eldritch Machinizations 2 and I have just discovered the seashelf crafting recipe is broken. The mod version we use is: apotheosis-0.2.81.jar. We run this on the Fabric API if that makes any difference.

**Comment by Safrodev** [comment]
The andesite should be replaced with a water bottle

**Comment by sjs262** [comment]
There is a similar issue for hellshelves as well--the andesite should be replaced with a potion of regeneration.

![image](https://user-images.githubusercontent.com/97537617/179624920-8677760c-d4ff-4ced-a883-5335ef9ed803.png)

**Comment by sjs262** [comment]
Ope, and look at that. The shelf of sight recipe is broken too:
![image](https://user-images.githubusercontent.com/97537617/179625659-ea669f0f-3a54-43f5-ad7f-5dacf12a950d.png)

**Comment by Safrodev** [comment]
The recipes do work, it may just be displaying incorrectly. I'm in a world currently and the potions show up in REI.
