### ISSUE TITLE
Unbreakable Potion Charms are unobtainable?

### ISSUE THREAD

**Issue by sjs262** [Safrodev/Apotheosis-Fabric#22]
It is written clearly in the Chronicle of Shadows that unbreakable charms can be obtained with fusion crafting in the enchantment table, but there are no resources online or in the book as to how to receive the enchantment. Still, experimenting with shelf combinations make getting infusion on hellshelves and seashelves easy enough, but I have yet to be able to figure out how to receive infusion on a potion charm.

Is this a bug? Are unbreakable charms purposefully disabled, and the book needs an update? Or am I simply not doing it right?

I have an enchantment table with maxed-out eterna, quanta, rectification and arcana, and still infusion only pops up for shelves, and not potion charms.

**Comment by sjs262** [comment]
In our modpack, REI does not show recipes for infusion. For the hellshelf for example, REI only shows tabs for the item's tag and the block drop--no enchantment table recipe. Is this a bug?

**Comment by Safrodev** [comment]
That's strange, I'm in a test world right now and the infusion recipes are displaying correctly.

**Comment by sjs262** [comment]
![image](https://user-images.githubusercontent.com/97537617/179887095-727bd84f-2c54-480b-a09c-ae863249359f.png)
This is what the item's recipes look like from my end.

Also, here is a setup I have for the enchanting table, and still no infusion. (50E, 5Q, 91.5A)
![image](https://user-images.githubusercontent.com/97537617/179887339-02ed292d-596b-42b7-ba1e-518303184ed2.png)
