### ISSUE TITLE
Newest update not allowing server to boot up

### ISSUE THREAD

**Issue by Gamerbolts** [Safrodev/Apotheosis-Fabric#23]
Hello I am creating a rather large modpack. I updated Apotheosis to the newest version 0.2.82 and my server will not start anymore. Client starts just fine. Here is the log since there is no crash report. https://pastebin.com/zrXwHhHR Any help is appreciated. Thank you!

**Comment by Safrodev** [comment]
Should be fixed in v0.2.83 :)
