### ISSUE TITLE
crash with betterend origins 

### ISSUE THREAD

**Issue by NullExistence1994** [Safrodev/Apotheosis-Fabric#3]
[crash-2022-05-11_14.08.49-client.txt](https://github.com/Safrodev/Apotheosis-Fabric/files/8667195/crash-2022-05-11_14.08.49-client.txt)

**Comment by Safrodev** [comment]
Some Apotheosis mixins are very bad with compat, I’ll change them to use Injects in the next update.

**Comment by NullExistence1994** [comment]
> Some Apotheosis mixins are very bad with compat; I’ll change them to use Injects in the next update.

thank you!i will install it first time

**Comment by Safrodev** [comment]
Fixed in v0.2.1
