### ISSUE TITLE
Apotheosis conflicts with the Vanilla Advancements/Achievement system

### ISSUE THREAD

**Issue by Azzmikaelson** [Safrodev/Apotheosis-Fabric#7]
Whenever I'm going to mine my first cobblestone in a new world usually it there would be an achievement pop up after that but it didn't. I crafted a iron pickaxe, no achievement unlocked. Even the "cover me with diamonds" didn't appeared. This only happens when I have Apotheosis installed

**Comment by Safrodev** [comment]
Fixed in v0.2.6
